
version: '3.1'

services:

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: joannis
      ME_CONFIG_BASICAUTH_PASSWORD: 123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo

networks:
  mongo: